### ISSUE TITLE
Please add types

### ISSUE THREAD

**Issue by EthanSK** [the-road-to-learn-react/use-state-with-callback#14]
No one uses javascript in 2020. Please add ts types

**Comment by rwieruch** [comment]
It's open source, you can actively contribute to the project.

**Comment by shunnmugam** [comment]
https://github.com/the-road-to-learn-react/use-state-with-callback/pull/16

**Comment by rwieruch** [comment]
@shunnmugam I merged your PR, but I get the following error on `npm run build`:

```
 [10] → npm run build

> use-state-with-callback@2.0.3 build /Users/mydspr/Developer/Repos/use-state-with-callback
> webpack --config ./webpack.config.js --mode=production

/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/copy-webpack-plugin/dist/index.js:44
      const logger = compilation.getLogger('copy-webpack-plugin');
                                 ^

TypeError: compilation.getLogger is not a function
    at /Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/copy-webpack-plugin/dist/index.js:44:34
    at SyncHook.eval [as call] (eval at create (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:1)
    at SyncHook.lazyCompileHook (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/webpack/lib/Compiler.js:580:30)
    at /Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/webpack/lib/Compiler.js:617:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/webpack/lib/Compiler.js:612:28)
    at /Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/webpack/lib/Compiler.js:284:11
    at Compiler.readRecords (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/webpack/lib/Compiler.js:479:11)
    at /Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/webpack/lib/Compiler.js:281:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/webpack/lib/Compiler.js:278:19
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.run (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/webpack/lib/Compiler.js:275:24)
    at processOptions (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/webpack-cli/bin/cli.js:362:14)
    at /Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/webpack-cli/bin/cli.js:373:3
    at Object.parse (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/yargs/yargs.js:567:18)
    at /Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/webpack-cli/bin/cli.js:375:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/mydspr/Developer/Repos/use-state-with-callback/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! use-state-with-callback@2.0.3 build: `webpack --config ./webpack.config.js --mode=production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the use-state-with-callback@2.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mydspr/.npm/_logs/2020-09-13T12_30_41_894Z-debug.log
```

**Comment by shunnmugam** [comment]
@rwieruch Please look into bellow PR
https://github.com/the-road-to-learn-react/use-state-with-callback/pull/17

**Comment by vyachsed** [comment]
Please publish it to npm.

**Comment by rwieruch** [comment]
Published @vyachsed @shunnmugam Thank you 👍
